name: Node Continuous Integration

on:
  push:
    branches-ignore:
      - gh-pages
  pull_request:
    branches-ignore:
      - gh-pages

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run linters
        run: npm run lint

  build-app:
    name: Build Application
    needs: run-linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run build
        run: npm run build
